import { FieldType } from "@prisma/client";
import {
  // Search,
  Phone,
  List,
  PenTool,
  Mail,
  Sliders,
  CalendarClock,
  ToggleLeft,
  Tag,
  AlignLeft,
  Star,
  CircleDot,
  CreditCard,
  CheckSquare,
  ListChecks,
  Calendar,
  Folder,
  Type,
  Hash,
  MapPin,
  ListPlus,
  Lock,
} from "lucide-react";

export const getFieldIcon = (fieldName: string) => {
  const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
    [FieldType.CHECKBOX]: CheckSquare,
    [FieldType.COMBOBOX]: ListChecks,
    [FieldType.DATE]: Calendar,
    [FieldType.DATETIME]: CalendarClock,
    [FieldType.FILE]: Folder,
    [FieldType.INPUT]: Type,
    [FieldType.OTP]: Hash,
    [FieldType.LOCATION]: MapPin,
    [FieldType.MULTISELECT]: ListPlus,
    [FieldType.PASSWORD]: Lock,
    [FieldType.PHONE]: Phone,
    [FieldType.EMAIL]: Mail,
    [FieldType.RADIO]: CircleDot,
    [FieldType.SELECT]: List,
    [FieldType.SIGNATURE]: PenTool,
    [FieldType.SLIDER]: Sliders,
    [FieldType.SMART_DATETIME]: CalendarClock,
    [FieldType.SWITCH]: ToggleLeft,
    [FieldType.TAGS]: Tag,
    [FieldType.TEXTAREA]: AlignLeft,
    // [FieldType.RATING]: Star,
    // [FieldType.RADIO_GROUP]: CircleDot,
    // [FieldType.CREDIT_CARD]: CreditCard,
  };
  return iconMap[fieldName] || Type;
};
